name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: moodmix/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./moodmix
    
    - name: Run security audit
      run: npm run audit-security
      working-directory: ./moodmix
    
    - name: Run security checks
      run: npm run security-check
      working-directory: ./moodmix
    
    - name: Run linter
      run: npm run lint
      working-directory: ./moodmix
    
    - name: Build project
      run: npm run build
      working-directory: ./moodmix
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    
    - name: Install Playwright
      run: npx playwright install --with-deps
      working-directory: ./moodmix
    
    - name: Run tests
      run: npm test
      working-directory: ./moodmix
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: moodmix/playwright-report/
        retention-days: 30